site_name: SISA Knowledge Base
docs_dir: docs
nav:
  - Home: index.md
  - How to Use:
      - License: how_to_use/license.md
      - Download: how_to_use/download.md
      - Impedance Scan: how_to_use/impedance_scan.md
      - Stability Analysis: how_to_use/stability_analysis.md
      - User Page: how_to_use/user_page.md
  - Feedback: feedback.md
  - Physics:
      - Impedance Scan: physics/impedance_scan.md
      - Stability Analysis: physics/stability_analysis.md

theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
      primary: teal
      accent: lime

plugins:
  - search
  - caption
  - bibtex:
      bib_file: 'docs/refs.bib'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - attr_list
  - md_in_html

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
